[project]
name = "anicrop"
version = "0.1.0"
description = "Programa para fazer stitch de animes"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.2",
    "opencv-python>=4.13.0.92",
    "ovld>=0.5.14",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ipython>=9.9.0",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
]


